//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ado.netcrud_operation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int productid { get; set; }
        public string productName { get; set; }
        public string category { get; set; }
        public decimal price { get; set; }
        public string remark { get; set; }
        public string email { get; set; }
    }
}
